hp/urls.py
from django.conf.urls import url,include
from django.urls import path
#from django.contrib.auth.views import login, logout, password_change, password_change_done
import django.contrib.auth.views

from . import views

__author__ = "Enrico Ferreguti"
__email__ = "enricofer@gmail.com"
__copyright__ = "Copyright 2017, Enrico Ferreguti"
__license__ = "GPL3"

urlpatterns = [
    url(r'^chiudi/$', views.chiudi, name='chiudi'),
    url(r'^riapri/$', views.riapri, name='chiudi'),
    url(r'^oauth/$', views.oauth, name='oauth'),
    url(r'^norme/$', views.wiki_norme, name='norme'),
    url(r'^outdate/$', views.outdate_norme, name='outdate'),
    url(r'^login/', django.contrib.auth.views.LoginView.as_view(), name='auth_login'),
    url(r'^logout/', django.contrib.auth.views.LogoutView.as_view(next_page=None), name='auth_logout'),
    #url(r'^change-password/$', password_change,{'template_name': 'registration/password_change_form.html', 'post_change_redirect': 'cdu_password_change_done'},name='cdu_change-password'),
    #url(r'^password-changed/$', password_change_done,{'template_name': 'registration/password_change_done.html'},name='cdu_password_change_done'),
]

istanze_proto/urls.py
from django.conf.urls import include, url, path
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from ajax_select import urls as ajax_select_urls
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views

from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

import hp.views

import django.views.static

__author__ = "Enrico Ferreguti"
__email__ = "enricofer@gmail.com"
__copyright__ = "Copyright 2017, Enrico Ferreguti"
__license__ = "GPL3"

admin.autodiscover()

urlpatterns = [
    url(r'^$', hp.views.home_page),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^taggit/', include('taggit_bulk.urls')),
    url(r'^admin/', include('massadmin.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^selectable/', include('selectable.urls')),
    url(r'^warp/', include('django_warp.urls')),
    url(r'^version/', include('version.urls')),
    url(r'^repertorio/', include('repertorio.urls')),
    url(r'^certificati/', include('certificati.urls')),
    url(r'^pua/', include('pua.urls')),
    url(r'^hp/', include('hp.urls')),
    url(r'^vincoli/', include('vincoli.urls')),
    url(r'^ajax_select/', include(ajax_select_urls)),
    url(r'^_nested_admin/', include('nested_admin.urls')),
    url('^accounts/', include('django.contrib.auth.urls')),
    # nell'attuale configurazione con DEBUG=False gunicorn serve in maniera errata i files statici binaria (mimetype sbagliato ??)
    # nell'attesa di configurare opportunamente nginx o apache django serve direttamente i files statici
    url(r'^static/(?P<path>.*)$', django.views.static.serve, {'document_root': settings.STATIC_ROOT, 'show_indexes': settings.DEBUG}),
    url(r'^documenti/(?P<path>.*)$', django.views.static.serve, {'document_root': settings.MEDIA_ROOT, 'show_indexes': settings.DEBUG}),
    path("favicon.ico",  RedirectView.as_view(url=staticfiles_storage.url("favicon.ico"))),
] #+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

pua/urls.py
from django.conf.urls import url,include
from . import views

from django.conf import settings
import django.contrib.auth.views

__author__ = "Enrico Ferreguti"
__email__ = "enricofer@gmail.com"
__copyright__ = "Copyright 2017, Enrico Ferreguti"
__license__ = "GPL3"

urlpatterns = [
    url(r'^validazione/$', views.valida_dxf, name='valida_dxf'),
    url(r'^promemoria/$', views.promemoria, name='promemoria'),
    url(r'^geojson/$', views.as_geojson, name='as_geojson'),
    url(r'^mappa/$', views.mappa_pua_tutto, name='as_map'),
    url(r'^sv/(\d+)/$', views.streetview_link, name='as_sv'),
    url(r'^mappa/(?P<PUAId>\d+)/$', views.mappa_pua_singolo, name='as_map'),
    url(r'^edit/(?P<PUAId>\d+)/$', views.modulo_pua, name='edit_pua'),
    url(r'^new/$', views.modulo_pua, name='new_pua'),
    url(r'^cat_osservazioni/$', views.new_cat_osservazioni, name='new_cat_osservazioni'),
    url(r'^login/', django.contrib.auth.views.LoginView),
    url(r'^logout/', django.contrib.auth.views.LogoutView),
]

pua/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desidered behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from __future__ import unicode_literals

from django.contrib.gis.db import models
from django.contrib.auth.models import User, Group
from django.core.exceptions import ValidationError
from django.contrib.gis.geos import Polygon
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver
from django.db.models import Q
from django.conf import settings
from urllib.parse import urlparse

import requests
import os
import time
import uuid
import re
import sys
import shutil
import datetime

__author__ = "Enrico Ferreguti"
__email__ = "enricofer@gmail.com"
__copyright__ = "Copyright 2017, Enrico Ferreguti"
__license__ = "GPL3"

tipologia_choice = (
    ('PUA',"PUA"),
    ("VPL","Vecchio Piano di lottizazione"),
    ("PI","Variante al Piano degli interventi"),
    ("MPI","Modifica al Piano degli interventi"),
    ('AdProg',"Accordo di programma"),
    ('AdPian',"Accordo di pianificazione"),
    ('Altro',"Altro"),
)

sottocategoria_choice = (
    ("PG","Piano guida"),
    ("DEL","Delimitazione d'ambito"),
    ("PdL","Piano di lottizzazione"),
    ("PdR","Piano di recupero"),
    ("PP","Piano particolareggiato"),
    ('PS',"Piano Speciale"),
    ('PeepErp',"PEEP"),
    ('SC',"Servizio civico"),
    ('PIRU',"PIRU-PIRUEA"),
    ('SUAP',"SUAP"),
    ('OP',"Opera pubblica"),
    ('AOU',"Atto unilaterale d'obbligo"),
    ('PPP',"Promemoria piani e progetti"),
)

stato_choice = (
    ("piano guida","01  piano guida"),
    ("ambito richiesto","02  ambito richiesto"),
    ("ambito delimitato","03  ambito delimitato"),
    ('istruttoria',"04  istruttoria"),
    ("adottato","05  adottato"),
    ('approvato',"06  approvato"),
    ('convenzionato',"07  convenzionato"),
    ('esecuzione',"08  in esecuzione"),
    ('collaudo parziale',"09 collaudo parziale"),
    ('collaudato',"10  collaudato"),
    ('sospeso',"10 sospeso"),
    ('revocato',"11 revocato"),
    ('decaduto',"12 decaduto"),
    ('ratificato',"13 ratificato"),
    ('autorizzato',"14 autorizzato"),
    ('archiviato',"15 archiviato"),
    ('contenzioso',"16 contenzioso"),
    ('attuato con PC',"17 Attuato in modalità diretta"),
    ('non rilevato',"99 non rilevato"),
)

tipo_allegato_choice = (
    ('DEL',"Delibera"),
    ('DET',"Determina"),
    ('PRE',"Documento preliminare"),
    ('COL',"Certificato di collaudo"),
    ('CON',"Convenzione"),
    ('CES',"Atto di cessione/asservimento aree"),
    ('AUO',"Atto unilaterale d'obbligo"),
    ('PVL',"Planimetria raster"),
    ('GEO',"Planimetria vettoriale"),
    ('PNO',"Documentazione di piano"),
    ('VAS',"Procedura V.A.S."),
    ('VNC',"Procedura V.Inc.A."),
    ('IDR',"Invarianza idraulica"),
    ('MON',"Monitoraggio"),
    ('PAR',"Parere"),
    ('SCP',"Scheda planivolumetrica"),
    ('PED',"Progetto edilizio"),
    ('ALT',"Altra documentazione"),
)

def check_url_ok(url):
    url = url or ""
    schema = url.split("://")[0]
    if schema in ("http", "https"):
        r = requests.head(url)
        if r.status_code == 200:
            return True
    return False

class pua(models.Model):

    def update_filename(instance, filename):
        path = "pua/planivol/%s" % instance.pk
        if not os.path.exists(path):
            os.makedirs(path)
        name,extension = os.path.splitext (filename)
        format = str(instance.data) +'_' + str(instance.cat) + '_'+ str(instance.titolo) + extension
        return os.path.join(path, format)

    gid = models.AutoField(primary_key=True)
    id_pua = models.CharField(max_length=5, blank=True, null=True)
    id_pguida = models.CharField(max_length=5, blank=True, null=True)
    objectid = models.IntegerField(blank=True, null=True)
    num_cad = models.CharField(max_length=20, blank=True, null=True)
    num_archiv = models.CharField(max_length=20, blank=True, null=True, verbose_name='Numero di archivio')
    tipologia = models.CharField(max_length=7,choices=tipologia_choice)
    sottocategoria = models.CharField(max_length=7,choices=sottocategoria_choice, blank=True, null=True)
    ditta = models.CharField(verbose_name=u"Denominazione interna", max_length=254, blank=True, null=True)
    prg_zona = models.CharField(max_length=100, blank=True, null=True)
    prg_norma = models.CharField(max_length=10, blank=True, null=True)
    delib_amb = models.CharField(max_length=50, verbose_name=u"Delibera di delim. d'ambito", blank=True, null=True)
    delib_ado = models.CharField(max_length=50, verbose_name=u"Delibera di adozione", blank=True, null=True)
    delib_appr = models.CharField(max_length=50, verbose_name=u"Delibera di approvazione", blank=True, null=True)
    delib_var = models.CharField(max_length=50, verbose_name=u"Delibera/e di variante", blank=True, null=True)
    stato = models.CharField(max_length=20 ,choices=stato_choice)
    convenzion = models.CharField(max_length=20, blank=True, null=True)
    shape_area = models.DecimalField(max_digits=10, decimal_places=3, blank=True, null=True)
    shape_leng = models.DecimalField(max_digits=10, decimal_places=3, blank=True, null=True)
    sup_perimetro = models.DecimalField(verbose_name=u"Superficie", max_digits=10, decimal_places=3, blank=True, null=True)
    vol_res = models.DecimalField(max_digits=10, decimal_places=3, blank=True, null=True)
    slp_no_res = models.DecimalField(max_digits=10, decimal_places=3, blank=True, null=True)
    collaudo = models.IntegerField(verbose_name=u"Anno di collaudo", blank=True, null=True)
    note = models.CharField(max_length=254, blank=True, null=True)
    determina = models.CharField(max_length=254, blank=True, null=True)
    cessione_a = models.CharField(max_length=254, blank=True, null=True)
    ubicazione = models.CharField(max_length=254, blank=True, null=True)
    quartiere = models.SmallIntegerField(blank=True, null=True)
    cod_via = models.IntegerField(blank=True, null=True)
    the_geom = models.MultiPolygonField(srid=3003, blank=True, null=True)
    sup_servizi = models.DecimalField(max_digits=10, decimal_places=3, blank=True, null=True)
    sup_verde = models.DecimalField(max_digits=10, decimal_places=3, blank=True, null=True)
    sup_park = models.DecimalField(max_digits=10, decimal_places=3, blank=True, null=True)
    planivol = models.ImageField(upload_to=update_filename, blank=True, null=True)
    infos  = models.ForeignKey('info',blank=True,null=True, related_name='infos', on_delete=models.SET_NULL) #da cancellare
    provvedimenti  = models.ForeignKey('provvedimento',blank=True,null=True, on_delete=models.SET_NULL) #da cancellare
    validazione = models.TextField(blank=True, null=True)
    zonizzazione = models.FileField(upload_to=update_filename,blank=True, null=True)
    sup_ambito = models.DecimalField(max_digits=10, decimal_places=3, blank=True, null=True)
    sup_privata = models.DecimalField(max_digits=10, decimal_places=3, blank=True, null=True)
    sup_cessioni = models.DecimalField(max_digits=10, decimal_places=3, blank=True, null=True)
    det_collaudo = models.CharField(max_length=254, verbose_name=u"Determina/e di collaudo", blank=True, null=True)
    vol_misto = models.DecimalField(max_digits=10, decimal_places=3, blank=True, null=True)
    denominazione = models.CharField(verbose_name=u"Denominazione ufficiale", max_length=254, blank=True, null=True)
    data_stato =  models.DateField( verbose_name=u"Data di cambiamento di stato", blank=True, null=True)
    anno_stato =  models.IntegerField( verbose_name=u"Anno di cambiamento di stato", blank=True, null=True)
    cdu = models.TextField(verbose_name=u"Testo personalizzato per CDU",blank=True, null=True)
    pubblicato = models.BooleanField(verbose_name=u"Pubblicato nell'applicazione CDU", default=True)
    coordinate_catastali = models.CharField(max_length=254, blank=True, null=True)
    pratiche_edilizie = models.CharField(max_length=100, blank=True, null=True)
    elaborati = models.CharField(verbose_name=u"Elaborati di piano", max_length=500, blank=True, null=True)
    convenzione = models.CharField(max_length=128, blank=True, null=True)
    planivol_raster = models.CharField(verbose_name=u"Planivolumetrico raster", max_length=128, blank=True, null=True)
    planivol_vector = models.CharField(verbose_name=u"Planivolumetrico vettoriale", max_length=128, blank=True, null=True)
    dds = models.DateField( verbose_name=u"Presentazione del documento del sindaco", blank=True, null=True)
    efficacia = models.DateField( verbose_name=u"Data di efficacia del piano", blank=True, null=True)
    version = models.CharField(verbose_name=u"Versione ESRI", max_length=30, blank=True, null=True)
    qc = models.CharField(verbose_name=u"Quadro Conoscitivo", max_length=128, blank=True, null=True)
    cat_osservazioni = models.ForeignKey('repertorio.catIstanze',verbose_name=u"Riferimento a osservazioni", blank=True,null=True, on_delete=models.SET_NULL, limit_choices_to=Q(termine=None)|Q(termine__gte=datetime.date.today()))
    curatore = models.ForeignKey(settings.AUTH_USER_MODEL,verbose_name=u"Referente interno",blank=True,null=True, on_delete=models.SET_NULL,limit_choices_to={'groups__name': 'pua'},)
    variante_rif = models.ForeignKey('pua',verbose_name=u"Variante di riferimento",blank=True,null=True, on_delete=models.SET_NULL,limit_choices_to={'tipologia': 'PI'},)
    decadenza = models.DateField( verbose_name=u"Data di decadenza del piano", blank=True, null=True)

    #link_elab = models.TextField(verbose_name=u"Link ad Elaborati di piano", blank=True, null=True)

pua/forms.py
from django import forms
from django.forms import ModelForm
from django.core.validators import RegexValidator
from bootstrap_datepicker_plus.widgets import DateTimePickerInput

from .models import pua,info,provvedimento

__author__ = "Enrico Ferreguti"
__email__ = "enricofer@gmail.com"
__copyright__ = "Copyright 2017, Enrico Ferreguti"
__license__ = "GPL3"


class UploadDXFForm(forms.Form):
    file_dxf = forms.FileField()

class PUAForm(ModelForm):
    class Meta:
        model = pua
        '''
        _widgets = {
            'id_pua': forms.TextInput(attrs={'class': 'form-control'}),
            'ditta': forms.TextInput(attrs={'class': 'form-control'}),
            'tipologia': forms.TextInput(attrs={'class': 'form-control'}),
            'richiedente_email': forms.TextInput(attrs={'class': 'form-control'}),
            'richiedente_telefono': forms.TextInput(attrs={'class': 'form-control'}),
            'protocollo_data': DateTimePickerInput(), 
            'protocollo_numero': forms.TextInput(attrs={'class': 'form-control'}),
            'coordinate_catastali': forms.TextInput(attrs={'class': 'form-control'}),
            'note': forms.Textarea(attrs={'class': 'form-control'}),
        }
        '''
        fields = ['id_pua','ditta', 'tipologia', 'the_geom', 'delib_amb', 'delib_appr', 'delib_var', 'det_collaudo', 'vol_res', 'slp_no_res', 'sup_servizi', 'sup_verde', 'sup_park', 'infos']

pua/templates/pua_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Piani urbanistici attuativi: validazione DXF</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'repertorio/css/bootstrap.min.css' %}" rel="stylesheet">
    {% block custom_style_link %}{% endblock %}
    <!-- Custom CSS -->
    <style>
    body {
        padding-top: 70px;
        /* Required padding for .navbar-fixed-top. Remove if using .navbar-static-top. Change if height of navigation changes. */
    }
    {% block custom_style_inline %}{% endblock %}
    </style>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- jQuery Version 1.11.1 -->
    {% comment %}<script src="{% static 'warp/js/jquery.js' %}"></script>{% endcomment %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'warp/js/bootstrap.min.js' %}"></script>
    
    {% block custom_js %}{% endblock %}
</head>

<body {% block onload %}{% endblock %}>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">{% block titolo %}{% endblock %}</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    {% block menu %}{% endblock %}
                </ul>
            <div class="pull-right">
                <ul class="nav navbar-nav">
                    <li>
                      
                      {% if user.is_anonymous %}
                      <a href="/warp/login/">login</a>
                      {% else %}
                      <a href="/warp/logout/">{{ user }} logout</a>
                      {% endif %}
                    </li>
                </ul>
            </div>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    
{% block content %}{% endblock %}
{% block contenuto %}{% endblock %}

    
    <!-- /.container -->
    {% block piedipagina %}{% endblock %}

</body>

</html>

pua/templates/pua_edit.html
{% extends 'pua_base.html' %}
{% load static %}
{% load l10n %}
{% comment %} {% endcomment %}

{% block custom_style_link %}
{% endblock %}
{% block custom_style_inline %}
.full {
    height: 100% !important;
    width: 100% !important;
}

#nav {
    margin: 5px;
    
}
{% endblock %}
{% block custom_js %}
{{ form.media }}
<script type="text/javascript">
  
$(document).ready(function(){
    
    $( '#prossimo' ).click( function(event) {
        $( "#submit" ).trigger( "click" );
    });
    
    $( '.fase' ).click( function(event) {
        window.location = "/certificati/"+event.target.id+"/{{idx}}/";
    });
    
    $( '#div_rilievo_raw' ).change( function(event) {
        $( '#id_coordinate_catastali' ).attr('value', "0/0")
    });
})


</script>
{% endblock %}
{% block onload %}{% endblock %}
{% block titolo %}
PUA {{ PUAId }}
{% endblock %}
{% block menu %}
<li>

</li>
{% endblock %}
{% block contenuto %}

<div class="container"> 
  <div class="row">
      <div class="col-md-12">
        <form id="dataset" action="/pua/{% if PUAId %}edit/{{PUAId}}/{% else %}new/{% endif %}" method="post" enctype="multipart/form-data">
          <div class="panel panel-default">
            <div class="panel-heading">Inserimento dati del Piano Urbanistico Attuativo</div>
            <div class="panel-body">
            
            {{ form }}
            
              <table class="full">
                {% for field in form.visible_fields %}
                <div id="div_{{ field.html_name }}" 
                     class="form-group{% if field.errors %} has-error{% endif %}">
                    {{ field.label_tag }}
                    {% localize on %}
                    {{ field }}
                    {% endlocalize %}
                    <div class="text-muted pull-right">
                        <small>{{ field.help_text }}</small>
                    </div>
                    <div class="help-block">
                        {{ field.errors }}
                    </div>
                </div>
                {% endfor %}
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}
                
                {% comment %}
                    {% if field.auto_id == 'id_protocollo_data' %}
                        <div class="form-group">
                            <div class='input-group date' id='datepicker_1'>
                                <input name="{{ field.name }}" type='text' class="form-control" />
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                </span>
                            </div>
                        </div>
                    {% else %}
                        {{ field }}
                    {% endif %}
                {% endcomment %}
                {% csrf_token %}
                
              </table>
            </div>
          </div>
        </form>
      </div>
  </div>
</div>

{% endblock %}
{% block piedipagina %}{% endblock %}

pua/templates/pua_ext_mappa.html
{% extends 'pua_base.html' %} {% load static %} {% load floppyforms %} {% comment %} {% endcomment %} {% block custom_style_link %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ol3/3.14.1/ol.min.css" />
<link rel="stylesheet" href="https://rawgit.com/walkermatt/ol3-layerswitcher/master/src/ol3-layerswitcher.css" /> {% endblock %} {% block custom_style_inline %}{% endblock %} {% block custom_js %}
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/ol3/3.15.1/ol.js"></script>
<script src="https://rawgit.com/walkermatt/ol3-layerswitcher/master/src/ol3-layerswitcher.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/proj4js/2.2.1/proj4.js"></script>
<script src="https://epsg.io/3003.js"></script>
<script src="https://fb.me/react-0.14.0.js"></script>
<script type="text/javascript">

    var targetExtent = [1716014, 5023919, 1737137, 5038662];

    var map_glob;
    var polyFeatures, polyOverlay;

    var targetProjection = new ol.proj.Projection({
        code: 'EPSG:3003',
        // The extent is used to determine zoom level 0. Recommended values for a
        // projection's validity extent can be found at http://epsg.io/.
        extent: targetExtent,
        units: 'm'
    });
    ol.proj.addProjection(targetProjection);

    var geoJson_convertitore = new ol.format.GeoJSON();

    var WKT_convertitore = new ol.format.WKT();

      /**
       * @param {number} n The max number of characters to keep.
       * @return {string} Truncated string.
       */
      String.prototype.trunc = String.prototype.trunc ||
          function(n) {
            return this.length > n ? this.substr(0, n - 1) + '...' : this.substr(0);
          };



    function init() {

        var maxResolution = 10;

        function getText(feature, resolution) {
            var text;
            if (resolution > maxResolution) {
                text = '';
            } else {
                text = feature.get('id_pua').toString()+"\n"+feature.get('ditta').trunc(20);;
            }
            return text;
        }

        function polygonStyleFunction(feature, resolution) {
            console.log(feature.get('idIstanza'));
            console.log(resolution);
            return new ol.style.Style({
                stroke: new ol.style.Stroke({
                    color: '#ff0000',
                    width: 3
                }),
                fill: new ol.style.Fill({
                    color: 'rgba(255, 255, 255, 0.3)'
                }),
                text: new ol.style.Text({
                    textAlign: "center",
                    textBaseline: "middle",
                    font: "Bold 12px Arial",
                    text: getText(feature, resolution),
                    fill: new ol.style.Fill({
                        color: "#ff0000"
                    }),
                    stroke: new ol.style.Stroke({
                        color: "#ffffff",
                        width: 3
                    })
                })
            });
        }

        //particelle overlay
        {% if features %}
        var polyObject = {% autoescape off %} {{features | safe}} {% endautoescape %};

        polyFeatures = new ol.Collection(new ol.format.GeoJSON().readFeatures(polyObject, {
            featureProjection: targetProjection
        }));
        {% else %}
        polyFeatures = new ol.Collection();
        {% endif %}

        polyOverlay = new ol.layer.Vector({
            source: new ol.source.Vector({
                features: polyFeatures
            }),
            title: 'perimetro relativo alla richiesta',
            style: polygonStyleFunction
        });

        console.log(polyOverlay.getSource().getExtent());

        map_glob = new ol.Map({
            layers: [

                {% include 'pua_baselayers.html' %}

                polyOverlay
            ],
            controls: ol.control.defaults().extend([
                //new ol.control.ScaleLine(),
                new ol.control.MousePosition(),
                new ol.control.OverviewMap()
            ]),
            target: 'map',
            view: new ol.View({
                projection: targetProjection,
                center: ol.extent.getCenter(targetExtent),
                zoom: 2
            })
        });

        var layerSwitcher = new ol.control.LayerSwitcher({
            tipLabel: 'Legenda' // Optional label for button
        });

        map_glob.getView().on('propertychange', function(e) {
           switch (e.key) {
              case 'resolution':
                console.log('resolution');
                console.log(e.oldValue);
                break;
           }
        });

        map_glob.on("click", function(e) {
            map_glob.forEachFeatureAtPixel(e.pixel, function (feature, layer) {
                //alert(feature.get('pk'))
                window.location.href="/admin/pua/pua/"+feature.get('pk').toString()+"/";
            })
        });

        map_glob.addControl(layerSwitcher);

        extent = polyOverlay.getSource().getExtent();
        map_glob.getView().fit(extent, map_glob.getSize());

    }

</script>
{% comment %}
{% endcomment %} {% endblock %} {% block onload %} onload="init()"{% endblock %} {% block titolo %}Mappa PUA{% endblock %} {% block menu %}

<li>
    <a href="/admin/pua/pua/">Lista db PUA</a>
</li>

{% endblock %} {% block contenuto %}


<div class="container-fluid">
    <div class="row-fluid">
        <div class="col-md-12">

            <div style="width:100%;height:700px" id="map"></div>

        </div>
    </div>
</div>

{% endblock %} {% block piedipagina %}{% endblock %}