django_warp/urls.py
from django.conf.urls import url,include
from . import views
#from warp.wms_config import testWmsView
from httpproxy.views import HttpProxy
#from revproxy.views import ProxyView
from django.conf import settings
import django.contrib.auth.views

__author__ = "Enrico Ferreguti"
__email__ = "enricofer@gmail.com"
__copyright__ = "Copyright 2017, Enrico Ferreguti"
__license__ = "GPL3"

urlpatterns = [
    url(r'^$', views.datasets_list, name='datasets_list'),
    url(r'^(\d+)/$', views.dataset_list, name='dataset_list'),
    url(r'^newdataset/$', views.dataset_form, name='dataset_new'),
    url(r'^removedataset/(\d+)/$', views.remove_dataset, name='dataset_remove'),
    url(r'^force_delete/(\d+)/$', views.force_raster_delete, name='force_raster_delete'),
    url(r'^updateimage/$', views.update_image, name='dataset_remove'),
    url(r'^emptytrash/$', views.empty_trash, name='empty_trash'),
    url(r'^vrtdataset/(\d+)/$', views.vrt_dataset, name='dataset_vrt'),
    url(r'^download_dataset/(\d+)/$', views.download_dataset, name='dataset_download'),
    url(r'^clone_dataset/(\d+)/$', views.clone_dataset, name='dataset_clone'),
    url(r'^editdataset/(?P<datasetId>\d+)/$', views.dataset_form, name='dataset_form'),
    url(r'^viewdataset/(?P<datasetId>\d+)/$', views.dataset_view, name='dataset_view'),
    url(r'^newimage/(?P<datasetId>\d+)/$', views.georef_start, name='georef_new'),
    url(r'^newimage_direct/(?P<datasetId>\d+)/$', views.georef_start_localhost, name='georef_new_localhost'),
    url(r'^trashimage/(\d+)/$', views.trash_image, name='georef_trash'),
    url(r'^recoverimage/(\d+)/$', views.recover_image, name='georef_recover'),
    url(r'^imgset/(?P<idx>\d+)/$', views.georef_start, name='georef_start'),
    url(r'^align/(?P<idx>\d+)/$', views.align, name='align'),
    url(r'^apply_align/$', views.georef_align, name='georef_align'),
    url(r'^apply/$', views.georef_apply, name='georef_apply'),
    url(r'^print/(\d+)/$', views.georef_print, name='georef_print'),
    url(r'^proxy/(?P<url>.*)', HttpProxy.as_view(base_url="")),
    url(r'^export/$', views.export, name='export'),
    #url(r'^proxy/(?P<path>.*)', ProxyView.as_view(upstream='https://')),
    url(r'^login/', django.contrib.auth.views.LoginView, name='auth_login'),
    url(r'^logout/', django.contrib.auth.views.LogoutView, name='auth_logout'),
    #url(r'raster/', include('raster.urls')),
    #url(r'^wms/$', testWmsView.as_view(), name='wms'),
]

hp/urls.py
from django.conf.urls import url,include
from django.urls import path
#from django.contrib.auth.views import login, logout, password_change, password_change_done
import django.contrib.auth.views

from . import views

__author__ = "Enrico Ferreguti"
__email__ = "enricofer@gmail.com"
__copyright__ = "Copyright 2017, Enrico Ferreguti"
__license__ = "GPL3"

urlpatterns = [
    url(r'^chiudi/$', views.chiudi, name='chiudi'),
    url(r'^riapri/$', views.riapri, name='chiudi'),
    url(r'^oauth/$', views.oauth, name='oauth'),
    url(r'^norme/$', views.wiki_norme, name='norme'),
    url(r'^outdate/$', views.outdate_norme, name='outdate'),
    url(r'^login/', django.contrib.auth.views.LoginView.as_view(), name='auth_login'),
    url(r'^logout/', django.contrib.auth.views.LogoutView.as_view(next_page=None), name='auth_logout'),
    #url(r'^change-password/$', password_change,{'template_name': 'registration/password_change_form.html', 'post_change_redirect': 'cdu_password_change_done'},name='cdu_change-password'),
    #url(r'^password-changed/$', password_change_done,{'template_name': 'registration/password_change_done.html'},name='cdu_password_change_done'),
]

istanze_proto/urls.py
from django.conf.urls import include, url, path
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from ajax_select import urls as ajax_select_urls
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views

from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

import hp.views

import django.views.static

__author__ = "Enrico Ferreguti"
__email__ = "enricofer@gmail.com"
__copyright__ = "Copyright 2017, Enrico Ferreguti"
__license__ = "GPL3"

admin.autodiscover()

urlpatterns = [
    url(r'^$', hp.views.home_page),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^taggit/', include('taggit_bulk.urls')),
    url(r'^admin/', include('massadmin.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^selectable/', include('selectable.urls')),
    url(r'^warp/', include('django_warp.urls')),
    url(r'^version/', include('version.urls')),
    url(r'^repertorio/', include('repertorio.urls')),
    url(r'^certificati/', include('certificati.urls')),
    url(r'^pua/', include('pua.urls')),
    url(r'^hp/', include('hp.urls')),
    url(r'^vincoli/', include('vincoli.urls')),
    url(r'^ajax_select/', include(ajax_select_urls)),
    url(r'^_nested_admin/', include('nested_admin.urls')),
    url('^accounts/', include('django.contrib.auth.urls')),
    # nell'attuale configurazione con DEBUG=False gunicorn serve in maniera errata i files statici binaria (mimetype sbagliato ??)
    # nell'attesa di configurare opportunamente nginx o apache django serve direttamente i files statici
    url(r'^static/(?P<path>.*)$', django.views.static.serve, {'document_root': settings.STATIC_ROOT, 'show_indexes': settings.DEBUG}),
    url(r'^documenti/(?P<path>.*)$', django.views.static.serve, {'document_root': settings.MEDIA_ROOT, 'show_indexes': settings.DEBUG}),
    path("favicon.ico",  RedirectView.as_view(url=staticfiles_storage.url("favicon.ico"))),
] #+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

django_warp/models.py
from django.db import models
from django.conf import settings
from django.contrib.gis.db import models
from slugify import slugify
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill
from django.dispatch import receiver
import os

__author__ = "Enrico Ferreguti"
__email__ = "enricofer@gmail.com"
__copyright__ = "Copyright 2017, Enrico Ferreguti"
__license__ = "GPL3"

def validate_file_extension(value):
    if not (value.file.content_type == 'image/png' or value.file.content_type == 'image/jpeg'):
        raise ValidationError(u'File not allowed: invalid extension')

# Create your models here.
class datasets(models.Model):
    name = models.CharField(max_length=50)
    slug = models.CharField(max_length=50,blank=True)
    epsg = models.IntegerField(default = '3857')
    extentLeft = models.FloatField(default = '-18000000.00')
    extentBottom = models.FloatField(default = '-8000000.00')
    extentRight = models.FloatField(default = '2000000.00')
    extentTop = models.FloatField(default = '15000000.00')
    baselayer = models.TextField(default = 'new ol.layer.Tile({\n    source: new ol.source.OSM()\n}),',blank=True)
    vrt = models.FileField(null=True,blank=True)
    transparency = models.BooleanField()
    #coverage = models.RasterField(blank=True,null=True)

    def publish(self):
        self.slug = slugify (self.name)
        self.save()

    def __str__(self):
        return self.name


class rasterMaps(models.Model):
    titolo = models.CharField(max_length=50)
    slug = models.CharField(max_length=50,blank=True)
    note = models.TextField(blank=True)
    dataset = models.ForeignKey('datasets',blank=True,null=True,related_name="current_dataset", on_delete=models.PROTECT) #,on_delete="PROTECT"
    datasetRecover = models.ForeignKey('datasets',blank=True,null=True,related_name="recover_dataset", on_delete=models.PROTECT) #,on_delete="PROTECT"
    sorgente = models.ImageField(upload_to='warp/', validators=[validate_file_extension])
    sorgente_thumbnail = ImageSpecField(source='sorgente',
                                      processors=[ResizeToFill(120, 120)],
                                      format='JPEG',
                                      options={'quality': 60})
    destinazione =  models.ImageField(upload_to='warp/', blank=True)
    webimg = models.ImageField(upload_to='warp/', blank=True)
    webimg_thumbnail = ImageSpecField(source='webimg',
                                      processors=[ResizeToFill(120, 120)],
                                      format='JPEG',
                                      options={'quality': 60})
    correlazione = models.TextField(blank=True)
    clipSorgente = models.TextField(blank=True)
    clipDestinazione = models.TextField(blank=True)

    def publish(self):
        self.slug = slugify (self.titolo)
        self.save()

    def __str__(self):
        return self.titolo

@receiver(models.signals.post_delete, sender=rasterMaps)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """Deletes file from filesystem
    when corresponding `mappeGeoreferenziate` object is deleted.
    """
    if instance.sorgente:
        sorgente_base, ext = os.path.splitext(instance.sorgente.path)

        if os.path.isfile(instance.sorgente.path):
            os.remove(instance.sorgente.path)

        if os.path.isfile(sorgente_base + ".geojson"):
            os.remove(sorgente_base + ".geojson")

        if os.path.isfile(sorgente_base + ".log"):
            os.remove(sorgente_base + ".log")

    elif instance.destinazione:
        destinazione_base, ext = os.path.splitext(instance.destinazione.path)

        if os.path.isfile(instance.destinazione.path):
            os.remove(instance.destinazione.path)
            build_vrt(instance.pk)

        if os.path.isfile(destinazione_base + ".geojson"):
            os.remove(destinazione_base + ".geojson")

    elif instance.webimg:
        webimg_base, ext = os.path.splitext(instance.webimg.path)

        if os.path.isfile(instance.webimg.path):
            os.remove(instance.webimg.path)

        if os.path.isfile(webimg_base + ".wld"):
            os.remove(webimg_base + ".wld")

def build_vrt(datasetId):
    dataset = datasets.objects.get(pk=datasetId)
    dataset_imgs = rasterMaps.objects.filter(dataset=dataset).order_by('pk')
    vrt_files = ""
    for img in dataset_imgs:
        vrt_files += '"'+settings.MEDIA_ROOT + str(img.destinazione) + '" '
    if vrt_files:
        vrtFileName = os.path.join(settings.MEDIA_ROOT,'warp',dataset.name) + '.vrt'
        buildVrtCmd = 'gdalbuildvrt -addalpha -hidenodata -overwrite "%s" %s' % (vrtFileName, vrt_files)
        #print("buildVrtCmd",buildVrtCmd)
        os.system(buildVrtCmd)
        dataset.vrt = os.path.relpath(vrtFileName,settings.MEDIA_ROOT)
    else:
        vrtFileName = ''
        dataset.vrt = None
    dataset.save()
    return vrtFileName

django_warp/forms.py
from django import forms
from django.forms import ModelForm
from .models import datasets

__author__ = "Enrico Ferreguti"
__email__ = "enricofer@gmail.com"
__copyright__ = "Copyright 2017, Enrico Ferreguti"
__license__ = "GPL3"


class UploadImmagineSorgenteForm(forms.Form):
    titolo = forms.CharField(max_length=50)
    note = forms.CharField(max_length=250)
    sorgente = forms.FileField()
    titolo.widget.attrs['class'] = 'form-control'
    note.widget.attrs['class'] = 'form-control'
    #sorgente.widget.attrs['class'] = 'form-control'

class BaseForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(BaseForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name[:6] == 'extent':
                field.widget.attrs['class'] = 'hidden'
            else:
                if field_name[:6] != 'transp':
                    field.widget.attrs['class'] = 'form-control'

class DatasetForm(BaseForm):
    class Meta:
        model = datasets
        exclude = ['slug',]

    def clean_name(self):
        name = self.cleaned_data['name']
        if name == "__TRASH":
            raise forms.ValidationError("'__TRASH' is a reserved dataset name")
        return name

django_warp/templates/collapse_list.html
{% extends 'warp_base.html' %}
{% load i18n %}
{% load l10n %}
{% load static %}
{% comment %} {% endcomment %}

{% block custom_style_link %}{% endblock %}
{% block custom_style_inline %}

.thumbs {border-style: solid; border-width: 1px;}
.panel {margin-bottom: 4px;}
#remove:hover {cursor: pointer; cursor: hand; color:blue}
#recover:hover {cursor: pointer; cursor: hand; color:blue}

{% endblock %}
{% block custom_js %}
<script src="/static/warp/js/bootbox.js"></script>
<script type="text/javascript">
$(document).ready(function() {
    $("tr").click(function(event) {
        if (event.target.tagName == 'TH'){
          window.location = "/warp/imgset/"+event.target.parentElement.id+"/";
        }
        else if (event.target.tagName == 'TD'){
          window.location = "/warp/imgset/"+event.target.parentElement.id+"/";
        }
        else if (event.target.tagName == 'IMG'){
          window.location = "/warp/imgset/"+event.target.parentElement.parentElement.id+"/";
        }
        else if (event.target.tagName == 'SPAN'){
            if (event.target.id == "remove"){
                bootbox.confirm("Do you really want to trash image? " + event.target.parentElement.parentElement.id.toString(), function(result) {
                    if (result) { window.location = "/warp/trashimage/" + event.target.parentElement.parentElement.id+"/"; }
                });
            }
            if (event.target.id == "recover"){
                window.location = "/warp/recoverimage/" + event.target.parentElement.parentElement.id+"/";
            }

        }
    });


    $("#new").click(function(event) {
        window.location = "/warp/newimage/{{dataset.pk}}/"
    });

});
</script>
{% endblock %}
{% block onload %}{% endblock %}
{% block titolo %}DATASET {{dataset.name}}{% endblock %}
{% block menu %}
<li>
<a href="/warp/">{% trans "datasets admin" %}</a>
</li>
{% endblock %}
{% block contenuto %}


<div class="container">
    <div class="col-md-12">
            <div id="accordion" role="tablist" aria-multiselectable="true">
                {% for dataset in groups %}
                <div class="panel panel-default">
                    <div class="panel-heading" role="tab" id="heading{{dataset.pk}}">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#table{{dataset.pk}}" aria-expanded="true" aria-controls="collapseOne">{{dataset.name}}</a>
                        </h4>
                    </div>
                    <div class="panel-collapse collapse {% if dataset.pk == choice %}in{% endif %}" role="tabpanel" aria-labelledby="heading{{dataset.pk}}" id="table{{dataset.pk}}">
                        <div class="panel-body">
                            {% if dataset.name != '__TRASH' %}<a type="button" class="btn btn-default" href="/warp/newimage/{{dataset.pk}}/">{% trans "New image" %}</a>{% endif %}
                            <table class="table table-hover">
                              <caption></caption>
                              <thead>
                                <tr>
                                  <th>#</th>
                                  <th>source</th>
                                  <th>target</th>
                                  <th>name</th>
                                  <th></th>
                                </tr>
                              </thead>
                              <tbody>
                                  {% for item in items %}
                                      {% if item.dataset.pk == dataset.pk %}
                                      <tr id="{{item.pk}}">
                                        <th scope="row">{{item.pk}}</th>
                                        <td>{% if item.sorgente %}<img class="thumbs" src="{{item.sorgente_thumbnail.url}}"/>{% endif %}</td>
                                        <td>{% if item.webimg %}<img class="thumbs" src="{{item.webimg_thumbnail.url}}"/>{% endif %}</td>
                                        <td>{{item.titolo}}</td>
                                        <td>
                                            {% if dataset.name != '__TRASH' %}
                                            <span id="remove" class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                            {% else %}
                                            <span id="recover" class="glyphicon glyphicon-share-alt" aria-hidden="true"></span>
                                            {% endif %}
                                        </td>
                                      </tr>
                                      {% endif %}
                                  {% endfor %}
                              </tbody>
                            </table>
                            {% if dataset.name != '__TRASH' %}<a type="button" class="btn btn-default" href="/warp/newimage/{{dataset.pk}}/">New image</a>{% endif %}
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
    </div>
</div>

{% endblock %}
{% block piedipagina %}{% endblock %}

django_warp/templates/dataset_form.html
{% extends 'warp_base.html' %}
{% load static %}
{% load i18n %}
{% load l10n %}
{% comment %} {% endcomment %}

{% block custom_style_link %}{% endblock %}
{% block custom_style_inline %}
.form-control {font-family:monospace;!important;font-size:0.9em;!important;}
{% endblock %}
{% block custom_js %}
<script type="text/javascript" src="/static/warp/js/ol.js"></script>
<script src="/static/warp/js/ol3-layerswitcher.js"></script>
<script src="/static/warp/js/proj4.js"></script>
<script src="https://epsg.io/{{ form.epsg.value }}.js"></script>
<script src="/static/warp/js/epsg.js"></script>
<script type="text/javascript">
{% localize off %}
var targetExtent = [{{ form.extentLeft.value }}, {{ form.extentBottom.value }}, {{ form.extentRight.value }}, {{ form.extentTop.value }}];
var leftBottom = [{{ form.extentLeft.value }},{{ form.extentBottom.value }}]
var rightTop = [{{ form.extentRight.value }},{{ form.extentTop.value }}]
{% endlocalize %}

var targetProjection;
var noInit = false;

function sleep(miliseconds) {
    var currentTime = new Date().getTime();
    while (currentTime + miliseconds >= new Date().getTime()) {
    }
}

{% comment %}
{% if form.epsg.value = 3857 or form.epsg.value = 4326 %}
var targetProjection = 'EPSG:{{ form.epsg.value }}';
{% else %}
var targetProjection = new ol.proj.Projection({
  code: 'EPSG:{{ form.epsg.value }}',
  // The extent is used to determine zoom level 0. Recommended values for a
  // projection's validity extent can be found at http://epsg.io/.
  extent: targetExtent,
  //units: 'm'
});
ol.proj.addProjection(targetProjection);
{% endif %}
{% endcomment %}

$(document).ready(function() {

    targetProjection = 'EPSG:'+$("#id_epsg").val().toString();

    if (proj4.defs(targetProjection) == undefined){
        console.log ("Invalid projection");
    } else {
        console.log(proj4.defs(targetProjection));
        var leftBottom_wgs84 = ol.proj.toLonLat(leftBottom, targetProjection);
        var rightTop_wgs84 = ol.proj.toLonLat(rightTop, targetProjection);
        $("#id_lonMin").val(leftBottom_wgs84[0]);
        $("#id_latMin").val(leftBottom_wgs84[1]);
        $("#id_lonMax").val(rightTop_wgs84[0]);
        $("#id_latMax").val(rightTop_wgs84[1]);
    }

    $('#update_button').click(function(eventObj) {
        $("#update").val("1");
        $('#submit').trigger('click');
    })

    $('#dataset').submit(function(eventObj) {

        console.log ("reprojection");

        var newTargetProjection = 'EPSG:'+$("#id_epsg").val().toString();
        var leftBottom_new = ol.proj.fromLonLat([parseFloat($("#id_lonMin").val()),parseFloat($("#id_latMin").val())], newTargetProjection); //parseFloat()
        var rightTop_new = ol.proj.fromLonLat([parseFloat($("#id_lonMax").val()),parseFloat($("#id_latMax").val())], newTargetProjection); //parseFloat()
        $("#id_extentLeft").val(leftBottom_new[0]);
        $("#id_extentBottom").val(leftBottom_new[1]);
        $("#id_extentRight").val(rightTop_new[0]);
        $("#id_extentTop").val(rightTop_new[1]);

    })

});

function onMoveEnd(evt) {
        if (noInit) {
            var map = evt.map;
            var new_ext = map.getView().calculateExtent(map.getSize());
            var leftBottom_wgs84 = ol.proj.toLonLat([new_ext[0],new_ext[1]], targetProjection);
            var rightTop_wgs84 = ol.proj.toLonLat([new_ext[2],new_ext[3]], targetProjection);
            $("#id_lonMin").val(leftBottom_wgs84[0]);
            $("#id_latMin").val(leftBottom_wgs84[1]);
            $("#id_lonMax").val(rightTop_wgs84[0]);
            $("#id_latMax").val(rightTop_wgs84[1]);
        } else {
            noInit = true
        }
    };

function init(){

    map = new ol.Map({
      layers: [

{{ form.baselayer.value | safe }}

      ],
      controls: ol.control.defaults().extend([
        new ol.control.MousePosition(),
        new ol.control.OverviewMap()
      ]),
      target: 'map',
      view: new ol.View({
        projection: targetProjection,
        center: ol.extent.getCenter(targetExtent),
        zoom: 2
      })
    });

    map.getView().fit(targetExtent, map.getSize());

    map.on('moveend', onMoveEnd);

}

</script>
{% endblock %}
{% block onload %} onload="init()"{% endblock %}
{% block titolo %}DATASET {% if idx %}{{idx}}{% endif %} {% if form %}{{form.name.value}}{% endif %} {% endblock %}
{% block menu %}
<li>
<a href="/warp/">dataset admin</a>
</li>
{% endblock %}
{% block contenuto %}


<div class="container">
    <div class="col-md-12">
            <form id="dataset" action="/warp/{% if idx %}editdataset/{{idx}}/{% else %}newdataset/{% endif %}" method="post" class="input-sm">

                <div class="panel-body">
                    <div class="panel panel-default col-md-4">
                        <div class="panel-body">
                           <form>
                              {% csrf_token %}
                            <div class="form-group">
                              <label for="id_name">Dataset name:</label>
                              {{form.name}}
                            </div>
                            <div class="form-group">
                              <label for="id_epsg">Coordinate system code (epsg):</label>
                              {{form.epsg}}
                              {{form.extentLeft}}
                              {{form.extentBottom}}
                              {{form.extentRight}}
                              {{form.extentTop}}
                            </div>
                            <div class="form-group">
                              <label for="lonMin">Minimum longitude:</label>
                              <input type="text" class="form-control" id="id_lonMin" name="lonMin" value="">
                            </div>
                            <div class="form-group">
                              <label for="latMin">Minimum latitude:</label>
                              <input type="text" class="form-control" id="id_latMin" name="latMin" value="">
                            </div>
                            <div class="form-group">
                              <label for="lonMax">Maximum longitude:</label>
                              <input type="text" class="form-control" id="id_lonMax" name="lonMax" value="">
                            </div>
                            <div class="form-group">
                              <label for="latMax">Maximum latitude:</label>
                              <input type="text" class="form-control" id="id_latMax" name="latMax" value="">
                            </div>
                            <div class="checkbox">
                                <label class="checkbox-inline">
                                {{form.transparency}}Force transparency on white background:</label>
                            </div>
                            <div class="form-group">
                              <label for="id_baselayer">Baselayer <br/> (Openlayers 3 valid javascript layer object):</label>
                              {{form.baselayer}}
                            </div>
                              <input type="text" class="hidden" id="update" name="update" value="0">
                              </br>
                              <input id="submit" type="submit" class="btn btn-default" value="Submit" />
                              </br>
                            </form>
                          </div>
                    </div>
                    <div class="col-md-8">
                        <div class="panel panel-default">
                          <div class="panel-heading"><strong>Dataset extension</strong></div>
                          <div class="panel-body">

                              <div style="width:100%;height:600px" id="map"></div>
                          </div>
                        </div>
                    </div>
                </div>

            </form>
    </div>
</div>

{% endblock %}
{% block piedipagina %}{% endblock %}

django_warp/templates/dataset_list.html
{% extends 'warp_base.html' %}
{% load i18n %}
{% load l10n %}
{% load static %}
{% comment %} {% endcomment %}

{% block custom_style_link %}{% endblock %}
{% block custom_style_inline %}{% endblock %}
{% block custom_js %}
<script type="text/javascript">
$(document).ready(function() {
    $("tr").click(function(event) {
        window.location = "/warp/{{dataset.pk}}/"+event.target.parentElement.id+"/";
    });
    
    $("#new").click(function(event) {
        window.location = "/warp/{{dataset.pk}}/newimage/"
    });
});
</script>
{% endblock %}
{% block onload %}{% endblock %}
{% block titolo %}DATASET {{dataset.name}}{% endblock %}
{% block menu %}{% endblock %}
{% block contenuto %}


<div class="container"> 
    <div class="col-md-12">
            <a type="button" class="btn btn-default" id="new">New raster image</a>
            <table class="table table-hover">
              <caption></caption>
              <thead>
                <tr>
                  <th>#</th>
                  <th>source</th>
                  <th>target</th>
                  <th>Image name</th>
                  <th>rasters</th>
                </tr>
              </thead>
              <tbody>
                  {% for item in items %}
                  <tr id="{{item.pk}}">
                    <th scope="row">{{item.pk}}</th>
                    <td>{% if item.sorgente %}<img src="{{item.sorgente_thumbnail.url}}"/>{% endif %}</td>
                    <td>{% if item.webimg %}<img src="{{item.webimg_thumbnail.url}}"/>{% endif %}</td>
                    <td>{{item.titolo}}</td>
                    <td>item.imgs</td>
                  </tr>
                  {% endfor %}
              </tbody>
            </table>
            <a type="button" class="btn btn-default" id="new">New raster image</a>
    </div>
</div>

{% endblock %}
{% block piedipagina %}{% endblock %}